#=== Data Parameters ===#
config: Amazon.csv
idd: ['Amazon-Health']
ood: ['Amazon-Camera'] 
encoders: ['albert-base-v1','distilbert-base-uncased', 'roberta-base', 'xlm-roberta-base', 'openai/clip-vit-base-patch32']
device: "cuda:1"
token_len: 512
verbose: True

#=== Network Parameters ===#
bottleneck_channels: 512
num_res_blocks: 5
time_embed_dim: 512
dropout: 0.0

#=== Optim ===#
epoch: 300
batch_size: 1024
lr: 0.00005


#=== Train ===#
beta_min: 0.1
beta_max: 20   
save_path: ./results/
method: All
