#=== Data Parameters ===#
ind: Amazon-Health
ood: ['Amazon-Music', 'Amazon-DVD', 'Amazon-Camera', 'Amazon-Books', 'Amazon-Software'] 
encoder: ['bert-base-uncased', 'roberta-base','xlm-roberta-base', 'clip']
device: cuda
token_len: 512

#=== Network Parameters ===#
bottleneck_channels: 512
num_res_blocks: 6
time_embed_dim: 256
dropout: 0.25

#=== Optim ===#
lr: 0.0002
beta1: 0.9
beta2: 0.999
eps: 1e-8
weight_decay: 0
warmup: 5000
grad_clip: 1
ema_rate: 0.9999

#=== Train ===#
continuous: True
reduce_mean: True
likelihood_weighting: False
beta_min: 0.1
beta_max: 20   
sigma_min: 0.01
sigma_max: 50
save_path: ./results/plot
method: Likelihood
