#=== Data Parameters ===#
config: SST2.csv
idd: ['IMDB']
ood: ['SST2'] 
encoders: ['clip']
device: cuda
token_len: 512
verbose: True

#=== Network Parameters ===#
bottleneck_channels: 512
num_res_blocks: 5
time_embed_dim: 512
dropout: 0.0

#=== Optim ===#
epoch: 500
batch_size: 1024
lr: 0.0002


#=== Train ===#
beta_min: 0.1
beta_max: 20   
save_path: ./results/
method: All
