#=== Data Parameters ===#
config: Yelp.csv
idd: ['IMDB']
ood: ['SST2'] 
encoders: ['albert-base-v1','distilbert-base-uncased','bert-base-uncased', 'roberta-base','xlm-roberta-base']
device: cuda
token_len: 512

#=== Network Parameters ===#
bottleneck_channels: 512
num_res_blocks: 5
time_embed_dim: 512
dropout: 0.0

#=== Optim ===#
epoch: 500
batch_size: 1024
lr: 0.0002


#=== Train ===#
beta_min: 0.1
beta_max: 20   
sigma_min: 0.01
sigma_max: 50
save_path: ./results/
method: ALL